In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/titanic.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
data.shape

(891, 12)

In [4]:
data.head(3)   ## first 3 records

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [5]:
data.tail()  ## last 5 records

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
data.sample()       ## one random record

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7,B37,C

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
## subset of dataframe

In [10]:
data["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [11]:
data[["Name"]].head()

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

In [12]:
data[["Name","Age","Fare"]].head()   ## for dataframe always take double bracket

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [13]:
### SLicing of dataframe

In [ ]:
data.iloc[:,:]    ## rows,columns

In [ ]:
data.iloc[5:,:]    ## row - 5 to last, all columns

In [ ]:
data.iloc[:10,:]    ## row - 0 to 9, all columns

In [ ]:
data.iloc[:10,3:7]

In [18]:
### display row = 2,4,5,8 | cols = Name, Fare, Embarked

In [ ]:
data.iloc[[2,4,5,8],[3,9,11]]

In [ ]:
data.iloc[[2,4,5,8]][["Name","Fare","Embarked"]]

In [24]:
## handle null values

In [25]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [26]:
### remove row/column having null value

In [ ]:
data.dropna(axis=0)   ## default value of axis = 0  (drop all rows where any column value is null)

In [ ]:
data.dropna(axis=1)   ## default value of axis = 0  (drop all columns where any row value is null)

In [ ]:
data.dropna(how='any')   ## default value of how = 'any'  (drop all rows where any column value is null)

In [ ]:
data.dropna(how='all')   ## default value of how = 'any'  (drop all rows where all column value is null)

In [ ]:
data.dropna(subset=["Age"])  ## (drop all rows where all Age value is null)

In [32]:
### fill null values

In [34]:
mean_age = round(data['Age'].mean())
mean_age

30

In [35]:
data['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [36]:
data['Age'] = data['Age'].fillna(mean_age)
data['Cabin'] = data['Cabin'].fillna("NA")
data['Embarked'] = data['Embarked'].fillna('Q')

In [ ]:
data.isnull().sum()

In [38]:
### Sort the data

In [ ]:
data.head()

In [ ]:
data_sorted = data.sort_values("Name",ascending=True)
data_sorted.head()

In [ ]:
data_sorted = data.sort_values("Name",ascending=False)
data_sorted.head()

In [42]:
data_sorted = data.sort_values("Name",ascending=False)
data_sorted = data_sorted.reset_index()
data_sorted.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,868,869,0,3,"van Melkebeke, Mr. Philemon",male,30.0,0,0,345777,9.5000,NA,S
1,153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NA,S
2,361,362,0,2,"del Carlo, Mr. Sebastiano",male,29.0,1,0,SC/PARIS 2167,27.7208,NA,C
3,282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5000,NA,S
4,286,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NA,S

In [43]:
## remove row/column

In [ ]:
data_sorted.head()

In [ ]:
data_sorted = data_sorted.drop([2,3],axis=0)  ## remove row
data_sorted

In [46]:
data_sorted = data_sorted.drop(["index"],axis=1)  ## remove column
data_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,869,0,3,"van Melkebeke, Mr. Philemon",male,30.0,0,0,345777,9.500,NA,S
1,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.500,NA,S
4,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.500,NA,S
5,560,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",female,36.0,1,0,345572,17.400,NA,S
6,423,0,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.875,NA,S

In [47]:
data_sorted.to_csv("mytitanic_data.csv",index=False)   ## export to csv

In [48]:
data_sorted.to_excel("mytitanic_data.xlsx",index=False)  ## export to excel

In [49]:
data_sorted.to_csv("mytitanic_data.csv",index=True)